language: python
python:
  - 2.6
  - 2.7
  - 3.3
before_install:
  - pip install -r requirements.txt
  - pip install pytest mock pretend freezegun
  - pip install -e .
  - pip install -q pep8
before_script:
  - pep8 pyicloud
script:
  - python setup.py test
